blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discord Community
    url: https://discord.gg/WZK29DB79R
    about: à¸žà¸¹à¸”à¸„à¸¸à¸¢ à¸ªà¸­à¸šà¸–à¸²à¸¡ à¸«à¸£à¸·à¸­à¸«à¸²à¸—à¸µà¸¡ à¹„à¸”à¹‰à¸—à¸µà¹ˆ Discord
